version: 2

jobs:
  build:
    working_directory: /go/src/github.com/marshallbrekka/go-u2fhost
    docker:
      - image: golang:1.14
    steps:
      - checkout
      - run:
          name: "Install native dependencies"
          command: |
            apt-get update && apt-get install libusb-1.0-0-dev --yes
      - run:
          name: Run unit tests
          command: |
            ./go.test.sh
      - run:
          name: Upload code coverage
          command: |
            bash <(curl -s https://codecov.io/bash)
